# Generated by Django 3.2 on 2022-02-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=254)),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('location_name', models.CharField(blank=True, max_length=254, null=True)),
                ('location_postcode', models.CharField(blank=True, max_length=8, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_tickets', models.IntegerField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
