# Generated by Django 3.2 on 2022-03-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_event_name_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
    ]
