# Generated by Django 3.2 on 2022-04-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ends',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]