# Generated by Django 3.2 on 2022-04-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220407_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='available_tickets',
            new_name='ticket_allocation',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_availability',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
