# Generated by Django 3.2 on 2022-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220409_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_availability',
            field=models.IntegerField(blank=True),
        ),
    ]
