# Generated by Django 3.2 on 2022-04-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_ticket_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ticket_availability',
            new_name='ticket_stock',
        ),
    ]
