# Generated by Django 3.2 on 2022-04-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
